### ISSUE TITLE
link to rnaGeneTissue no longer available 

### ISSUE THREAD

**Issue by ManonMartin** [lgatto/hpar#15]
The previous link to download rnaGeneTissue (https://www.proteinatlas.org/download/rna_tissue.tsv.zip) is no longer available. Which dataset should be used instead?

**Comment by lgatto** [comment]
I think it has been renames [normal_tissue.tsv.zip](https://www.proteinatlas.org/download/normal_tissue.tsv.zip).

**Comment by ManonMartin** [comment]
No, this is actually another downloaded dataset. It could either be: [rna_tissue_consensus.tsv.zip](https://www.proteinatlas.org/download/rna_tissue_consensus.tsv.zip), [rna_tissue_hpa.tsv.zip](https://www.proteinatlas.org/download/rna_tissue_hpa.tsv.zip), [rna_tissue_gtex.tsv.zip](https://www.proteinatlas.org/download/rna_tissue_gtex.tsv.zip) or [rna_tissue_fantom.tsv.zip](https://www.proteinatlas.org/download/rna_tissue_fantom.tsv.zip)

**Comment by lgatto** [comment]
Not sure... maybe each of these should be added to hpar.

**Comment by ManonMartin** [comment]
Yes. should we keep the dataset rnaGeneTissue as rnaGeneTissue21.0 ?

**Comment by lgatto** [comment]
yes
