### ISSUE TITLE
update to more recent R version needed

### ISSUE THREAD

**Issue by ManonMartin** [lgatto/hpar#4]
I get this message when I am (locally) installing `hpar`:  
─  looking to see if a ‘data/datalist’ file should be added NB: this package now depends on R (>= 3.5.0) WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘hpar/data/hpaCancer.rda’  ‘hpar/data/hpaNormalTissue.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘hpar/data/hpaSubcellularLoc.rda’  ‘hpar/data/rnaGeneCellLine.rda’  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘hpar/data/rnaGeneTissue.rda’  ‘hpar/inst/extdata/hpaRelease.rda’

Should I update accordingly the R version in the Depends field?

**Comment by lgatto** [comment]
Yes please
